## The Perceptron

* Its the simplest ANN architecture. It was invented by Frank Rosenblatt in 1957 and published as `Rosenblatt, Frank (1958), The Perceptron: A Probabilistic Model for Information Storage and Organization in the Brain, Cornell Aeronautical Laboratory, Psychological Review, v65, No. 6, pp. 386â€“408. doi:10.1037/h0042519`
* It has different architecture then the first neuron that we have seen above. Its known as threshold logic unit(TLU) or linear threshold unit (LTU).
* Here inputs are not just binary.
* Lets see the architecture shown below -
    
    <a title="Chrislb / CC BY-SA (http://creativecommons.org/licenses/by-sa/3.0/)" href="https://commons.wikimedia.org/wiki/File:ArtificialNeuronModel_english.png"><img width="1024" alt="ArtificialNeuronModel english" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/ArtificialNeuronModel_english.png/1024px-ArtificialNeuronModel_english.png"></a>

* Common activation functions used for Perceptrons are (with threshold at 0)-

$$step(z)\ or\ heaviside(z) = \left\{\begin{matrix}
0 & z<0\\
1 & z\geq 0
\end{matrix}\right.$$

- In the further tutorials we will study more about activation functions, for now we can understand **activation functions** are mathematical equations that are applied to the output of a neural network node, in order to introduce non-linearity into the output. These functions help the neural network to learn and model complex patterns in the data. Activation functions are a key component of artificial neural networks and are used to determine the output of each neuron based on the input it receives. There are many types of activation functions, including **sigmoid, ReLU, tanh, and softmax**, each with their own unique properties and use cases.

In [6]:
import numpy as np
class Perceptron:
       #epochs - iterations(no. of times we will update the weights)
       #eta - learning rate
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights: {self.weights}")
    self.eta = eta
    self.epochs = epochs

  def activationFunction(self, inputs, weights):
            #it gives dot product
    z = np.dot(inputs, weights)
            #threshold - if z > 0 then 1 otherwise 0
    return np.where(z > 0 , 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # concactination
    print(f"X_with_bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch: {epoch}")
      y_hat = self.activationFunction(X_with_bias, self.weights)
      print(f"predicted value: \n{y_hat}")
      error = self.y - y_hat
      print(f"error: \n{error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"updated weights: \n{self.weights}")
      print("#############\n")

  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
    return self.activationFunction(X_with_bias, self.weights)

## AND OPERATION

In [7]:
import pandas as pd
data = {"x1":[0,0,1,1] , "x2":[0,1,0,1] ,"y":[0,0,0,1]}
AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [8]:
X = AND.drop("y",axis = 1)
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [9]:
y = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [10]:
model = Perceptron(eta =0.5,epochs = 10)
model.fit(X,y)

self.weights: [-3.82540479e-05  3.50324514e-05 -4.27631557e-05]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value:
[1 1 1 1]
error:
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[-0.50003825 -0.49996497  1.49995724]
#############

for epoch: 1
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[-3.82540479e-05  3.50324514e-05  9.99957237e-01]
#############

for epoch: 2
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.49996175 0.50003503 0.49995724]
#############

for epoch: 3
predicted value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[-3.82540479e-05  3.50324514e-05  1.49995724e+00]
#############

for epoch: 4
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.49996175 0.50003503 0.99995724]
#############

for epoch: 5
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49996175 0.50003503 0.99995724]
#############

for epoch: 6
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49996175 0.50003503 0.99995724]
#############

for epoch: 7
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49996175 0.50003503 0.99995724]
#############

for epoch: 8
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49996175 0.50003503 0.99995724]
#############

for epoch: 9
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49996175 0.50003503 0.99995724]
#############

In [11]:
model.predict(X)

array([0, 0, 0, 1])

In [12]:
model.weights

array([0.49996175, 0.50003503, 0.99995724])

## OR OPERATION

In [13]:
data = {"x1":[0,0,1,1] , "x2":[0,1,0,1] ,"y":[0,1,1,1]}
OR = pd.DataFrame(data)
OR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [14]:
X = OR.drop("y",axis =1)
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [16]:
y = OR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  1

In [17]:
model = Perceptron(eta = 0.5 , epochs = 10)
model.fit(X,y)

self.weights: [-7.55104712e-05 -1.73635280e-04  4.49812986e-05]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights:
[ 0.99992449  0.99982636 -1.49995502]
#############

for epoch: 1
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[ 0.99992449  0.99982636 -0.99995502]
#############

for epoch: 2
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[ 0.99992449  0.99982636 -0.49995502]
#############

for epoch: 3
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[9.99924490e-01 9.99826365e-01 4.49812986e-05]
#############

for epoch: 4
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[9.99924490e-01 9.99826365e-01 4.49812986e-05]
#############

for epoch: 5
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[9.99924490e-01 9.99826365e-01 4.49812986e-05]
#############

for epoch: 6
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[9.99924490e-01 9.99826365e-01 4.49812986e-05]
#############

for epoch: 7
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[9.99924490e-01 9.99826365e-01 4.49812986e-05]
#############

for epoch: 8
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[9.99924490e-01 9.99826365e-01 4.49812986e-05]
#############

for epoch: 9
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[9.99924490e-01 9.99826365e-01 4.49812986e-05]
#############

In [18]:
model.predict(X)

array([0, 1, 1, 1])

In [20]:
model.weights

array([9.99924490e-01, 9.99826365e-01, 4.49812986e-05])

## XOR OPERATION

In [21]:
data = {"x1":[0,0,1,1] , "x2":[0,1,0,1] ,"y":[0,1,0,1]}
XOR = pd.DataFrame(data)
XOR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  0
3   1   1  1

In [22]:
X = OR.drop("y",axis =1)
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [23]:
y = OR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  1

In [24]:
model = Perceptron(eta = 0.5 , epochs = 50)
model.fit(X,y)

self.weights: [2.69632387e-04 3.43397062e-05 1.80693968e-05]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 1
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 2
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 3
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 4
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 5
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 6
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 7
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 8
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 9
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 10
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 11
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 12
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 13
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 14
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 15
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 16
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 17
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 18
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 19
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 20
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 21
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 22
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 23
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 24
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 25
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 26
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 27
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 28
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 29
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 30
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 31
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 32
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 33
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 34
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 35
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 36
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 37
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 38
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 39
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 40
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 41
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 42
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 43
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 44
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 45
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 46
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 47
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 48
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

for epoch: 49
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[2.69632387e-04 3.43397062e-05 1.80693968e-05]
#############

In [25]:
model.predict(X)

array([0, 1, 1, 1])

## It is not working for XOR